"""
Django settings for TaskFlow project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-od^l_aj)1$ipl-0e!s%_#_7$dp(o3u0bwpuk%8ps4t&#lw(xuc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'testserver',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts.apps.AccountsConfig",
    "courses.apps.CoursesConfig",
    "tasks.apps.TasksConfig",
    "notifications.apps.NotificationsConfig",
    "dashboard.apps.DashboardConfig",
]

AUTH_USER_MODEL = "accounts.User"

AUTH_USER_MODEL = "accounts.User"
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TaskFlow.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # مجلدات Templates العامة للمشروع.
        # Templates الموجودة داخل التطبيقات
        # يتم اكتشافها تلقائيًا بسبب APP_DIRS=True.
        "DIRS": [],

        # البحث تلقائيًا داخل templates لكل تطبيق.
        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'TaskFlow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# اللغة الافتراضية للمشروع: العربية
LANGUAGE_CODE = 'ar'

# المنطقة الزمنية: توقيت الرياض / السعودية
TIME_ZONE = 'Asia/Riyadh'

# تفعيل نظام الترجمة في Django
USE_I18N = True

# استخدام المناطق الزمنية
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ==========================================
# Static Files
# ==========================================

# الرابط المستخدم للوصول إلى الملفات الثابتة
# ==========================================
# Static Files
# ==========================================

# رابط الملفات الثابتة
STATIC_URL = "/static/"

# المجلد الذي نضع فيه ملفات CSS و JavaScript والصور الثابتة
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# المجلد الذي يجمع Django داخله الملفات عند تشغيل collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"


# ==========================================
# Media Files
# ==========================================

# رابط الملفات التي يرفعها المستخدم
MEDIA_URL = "/media/"

# المجلد الذي يتم حفظ الملفات المرفوعة بداخله
MEDIA_ROOT = BASE_DIR / "media"


# ==========================================
# Media Files
# ==========================================

# الرابط المستخدم للوصول إلى الملفات المرفوعة
MEDIA_URL = "/media/"

# مكان تخزين الملفات المرفوعة
MEDIA_ROOT = BASE_DIR / "media"
