# Generated by Django 6.0.7 on 2026-08-09 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المادة')),
                ('code', models.CharField(blank=True, help_text='مثال: CSCI-301', max_length=30, verbose_name='رمز المادة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('semester', models.CharField(choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني'), ('summer', 'الفصل الصيفي')], default='first', max_length=20, verbose_name='الفصل الدراسي')),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, help_text='مثال: 2026', null=True, verbose_name='السنة الدراسية')),
                ('color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='يجب إدخال اللون بصيغة صحيحة مثل #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='لون المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مادة نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='course_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name', 'semester', 'academic_year'), name='unique_course_per_user_semester_year')],
            },
        ),
    ]
