# Generated by Django 6.0.7 on 2026-08-09 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المهمة')),
                ('task_type', models.CharField(choices=[('assignment', 'واجب'), ('project', 'مشروع'), ('exam', 'اختبار'), ('review', 'مراجعة'), ('other', 'أخرى')], default='assignment', max_length=20, verbose_name='نوع المهمة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'مرتفعة'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('todo', 'لم تبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='todo', max_length=20, verbose_name='حالة المهمة')),
                ('due_date', models.DateTimeField(verbose_name='موعد التسليم')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إكمال المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course', verbose_name='المادة الدراسية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['due_date', '-priority'],
                'indexes': [models.Index(fields=['user', 'status'], name='task_user_status_idx'), models.Index(fields=['user', 'due_date'], name='task_user_due_idx'), models.Index(fields=['course', 'status'], name='task_course_status_idx')],
            },
        ),
    ]
