# Generated by Django 6.1 on 2026-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'واجب'), ('quiz', 'كويز'), ('midterm', 'اختبار نصفي'), ('final', 'اختبار نهائي'), ('project', 'مشروع'), ('presentation', 'عرض تقديمي'), ('exam', 'اختبار'), ('review', 'مراجعة'), ('other', 'أخرى')], default='assignment', max_length=20, verbose_name='نوع المهمة'),
        ),
    ]
